# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
'$schema': https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 4
final_space: true
secondary_prompt:
  template: '❯❯ '
  foreground: magenta
  background: transparent
transient_prompt:
  template: '❯ '
  background: transparent
  foreground_templates:
    - '{{ if gt .Code 0 }}red{{ end }}'
    - '{{ if eq .Code 0 }}magenta{{ end }}'
console_title_template: '{{ .Shell }} in {{ .Folder }}'
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: plain
        foreground: blue
        properties:
          cache_duration: none
          style: full
        template: '{{ .Path }}'
      - type: git
        style: plain
        foreground: p:grey
        properties:
          cache_duration: none
          fetch_status: true
        template: ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
        background: transparent
      - type: python
        style: plain
        foreground: '#ffd742'
        properties:
          cache_duration: none
          display_mode: context
        template: " \ue235 {{ if .Venv }}{{ .Venv }}@{{ end }}{{ .Full }}"
      - type: go
        style: plain
        foreground: cyan
        properties:
          cache_duration: none
        template: " \u202d{{ .Full }} "
    newline: true
  - type: rprompt
    overflow: hidden
    segments:
      - properties:
          cache_duration: none
          threshold: 5000
        template: '{{ .FormattedMs }}'
        foreground: yellow
        background: transparent
        type: executiontime
        style: plain
  - type: prompt
    alignment: left
    segments:
      - type: text
        style: plain
        foreground: magenta
        template: '{{ if .Env.TBX_NAME }}🧰{{ .Env.TBX_NAME }} {{ end }}'
      - type: text
        style: plain
        foreground: magenta
        properties:
          cache_duration: none
        template: ❯
    newline: true
tooltips:
  - template: 󱃾{{ upper ((split "-" .Cluster)._1) }}
    foreground: cyan
    type: kubectl
    style: plain
    tips:
      - kubectl
      - oc
