# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
console_title_template: '{{ .Shell }} in {{ .Folder }}'

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        foreground: blue
        template: '{{ .Path }}'
        properties:
          style: full
      - type: git
        style: plain
        foreground: grey
        template: ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
        properties:
          fetch_status: true
      - type: python
        style: plain
        foreground: yellow
        template: '  {{ if .Venv }}{{ .Venv }}@{{ end }}{{ .Full }}'
        properties:
          display_mode: context
      - type: go
        style: plain
        foreground: cyan
        template: ' ‭ﳑ {{ .Full }} '
  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        background: transparent
        template: '{{ .FormattedMs }}'
        properties:
          threshold: 5000
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground: magenta
        template: ❯

transient_prompt:
  foreground_templates:
    - '{{ if gt .Code 0 }}red{{ end }}'
    - '{{ if eq .Code 0 }}magenta{{ end }}'
  background: transparent
  template: '❯ '

secondary_prompt:
  foreground: magenta
  background: transparent
  template: '❯❯ '

tooltips:
  - type: kubectl
    style: plain
    foreground: cyan
    template: 'ﴱ {{ upper ((split "-" .Cluster)._1) }}/{{ .Namespace }}'
    tips:
      - kubectl
      - oc
